import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/0_All/Navbar";
import Footer from "@/components/0_All/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/Theme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning={true}
    >
      <body
        className="min-h-full flex flex-col overflow-x-hidden"
      >
        <ThemeProvider>
          <Navbar className="sticky top-0 w-full z-90" />
          <main className="flex min-h-0 flex-1 flex-col">{children}</main>
          <Footer />
          <Toaster />
          <SpeedInsights />
        </ThemeProvider>
      </body>
    </html>
  );
}
